### ISSUE TITLE
Can you add a feature to make queues 

### ISSUE THREAD

**Issue by ghost** [kivaar/long-live#5]
Hey there.

I was just wondering if its possible to add a feature where we are able to make queues of download, (Meaning it starts downloading the pages we added 1 after another as the page before it ends)

**Comment by kivaar** [comment]
Hey Nooraldeen! I think that should be pretty straightforward to add in. Could you please tell me how you're running the Python code or whether you're using the .exe so I know where to make the updates? I can have a look over the next few weeks :)

**Comment by ghost** [comment]
Hey, thanks for the quick reply

I am not a programmer, just a nomral consumer I use the version downloded straight from the Github releases page called long-live.exe 

If I am on an older version then I am sorry about the troubles, all I am looking for is just to make using the program easier and more effiecnt by adding a queue feature

Thanks for your time <3

**Comment by kivaar** [comment]
No worries at all! I'll have a look and let you know when I've added it into a new release

**Comment by kivaar** [comment]
Hey @Nooraldeen02, I've uploaded a new release for you to try: [v0.2.0](https://github.com/kivaar/long-live/releases/tag/v0.2.0)

There's a new "Bulk" tab in the program where you can enter multiple URLs on separate lines. Unfortunately, I don't think I can increase the size of the box due to a limitation in the wrapper that I'm using. I found it easier to list all the URLs in a notepad first and then paste them in all at once.

Let me know if it works the way you need it to :)

**Comment by ghost** [comment]
Thanks for your time @kivaar it works perfectly as I was looking for 

The size of the box does not matter its just a visual thing, what matters is that it works perfectly without any issues so far

**Comment by kivaar** [comment]
That's great! You're very welcome
